# Generated by Django 6.0.5 on 2026-05-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('area', models.DecimalField(decimal_places=2, help_text='Dönüm', max_digits=8)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('iscilik', 'İşçilik'), ('gubre', 'Gübre'), ('sulama', 'Sulama'), ('ilac', 'İlaç'), ('yakit', 'Yakıt'), ('ekipman', 'Ekipman'), ('diger', 'Diğer')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fields.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('cilek', 'Çilek'), ('elma', 'Elma'), ('kiraz', 'Kiraz'), ('seftali', 'Şeftali'), ('diger', 'Diğer')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('adet', 'Adet'), ('lt', 'Lt'), ('paket', 'Paket'), ('m', 'Metre')], default='kg', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='fields.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
