# Generated by Django 6.0.5 on 2026-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_field_user_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fieldexpense',
            index=models.Index(fields=['field', 'date'], name='fields_fiel_field_i_74b41e_idx'),
        ),
    ]
