# Generated by Django 6.0.5 on 2026-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
