# Generated by Django 6.0.5 on 2026-06-09 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_customers_c_user_id_515ba1_idx_and_more'),
        ('dashboard', '0006_expense'),
        ('fields', '0004_fieldexpense_fields_fiel_field_i_74b41e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['user', 'date'], name='dashboard_c_user_id_6f9691_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'direction'], name='dashboard_c_custome_b57bea_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='dashboard_e_user_id_ac5aae_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='dashboard_e_user_id_9c7667_idx'),
        ),
    ]
