# Generated by Django 6.0.5 on 2026-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kg'), ('lt', 'Lt'), ('m', 'Metre'), ('paket', 'Paket')], default='adet', max_length=10),
        ),
    ]
