# Generated by Django 6.0.5 on 2026-05-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_landtransaction'),
        ('transactions', '0006_transaction_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fields.field', verbose_name='Tarla'),
        ),
    ]
