# Generated by Django 6.0.5 on 2026-06-05 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_field_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.CharField(choices=[('cilek', 'Çilek'), ('elma', 'Elma'), ('kiraz', 'Kiraz'), ('seftali', 'Şeftali'), ('diger', 'Diğer'), ('gubre', 'Gübre'), ('fide', 'Fide'), ('boru', 'Boru'), ('diger', 'Diğer')], max_length=20),
        ),
    ]
