# Generated by Django 6.0.5 on 2026-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_date_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('sale', 'Satış'), ('purchase', 'Alış'), ('both', 'Her İkisi')], max_length=10)),
                ('default_unit', models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kg'), ('lt', 'Lt'), ('m', 'Metre'), ('paket', 'Paket')], default='kg', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
