# Generated by Django 6.0.5 on 2026-06-09 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_customers_c_user_id_515ba1_idx_and_more'),
        ('fields', '0004_fieldexpense_fields_fiel_field_i_74b41e_idx'),
        ('transactions', '0010_seed_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'date'], name='transaction_custome_70b027_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'type'], name='transaction_custome_0dd517_idx'),
        ),
    ]
