# Generated by Django 6.0.5 on 2026-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_transaction_user_id_8af7f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, default='📦', max_length=10),
        ),
    ]
