# Generated by Django 6.0.5 on 2026-06-09 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'name'], name='customers_c_user_id_515ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'customer_type'], name='customers_c_user_id_15066e_idx'),
        ),
    ]
